package com.example.dechuan.model.vehicle;

import com.example.dechuan.utils.DateUtils;

import java.sql.Timestamp;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vehicle_interaction
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Vehicle {
    /**
     * 主键
     */
    private Integer vInKy;

    /**
     *  工单主键
      */

    private Integer woKy;
    /**
     * 车牌
     */
    private String carNo;

    /**
     * 车辆状态
     */
    private Integer viStatus;

    /**
     * 车辆进入时间
     */
    private Timestamp vehicleTime;


    public Integer getWoKy() {
        return woKy;
    }

    public void setWoKy(Integer woKy) {
        this.woKy = woKy;
    }

    public Integer getvInKy() {
        return vInKy;
    }

    public void setvInKy(Integer vInKy) {
        this.vInKy = vInKy;
    }

    public String getCarNo() {
        return carNo;
    }

    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    public Integer getViStatus() {
        return viStatus;
    }

    public void setViStatus(Integer viStatus) {
        this.viStatus = viStatus;
    }
    public String getVehicleTime() {
        return DateUtils.formatDate(vehicleTime, "yyyy-MM-dd HH:mm:ss");
    }

        public void setVehicleTime(String vehicleTime) {
            this.vehicleTime = Timestamp.valueOf(vehicleTime);
        }

}