package com.example.dechuan.model.usermanage;

import com.example.dechuan.utils.DateUtils;

import java.sql.Timestamp;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbeh_dc_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleManage {

    /**
     * 主键
     */
    private Integer roleKy;
    /**
     * 角色名
     */

    private String roleName;
    /**
     * 角色代码
     */

    private String roleCode;

    /**
     * 新增时间
     */
    private Timestamp insetTime;


    public Integer getRoleKy() {
        return roleKy;
    }


    public void setRoleKy(Integer roleKy) {
        this.roleKy = roleKy;
    }


    public String getRoleName() {
        return roleName;
    }


    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


    public String getRoleCode() {
        return roleCode;
    }


    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }


    public String getInsetTime() {
        return DateUtils.formatDate(insetTime, "yyyy-MM-dd HH:mm:ss");
    }

    public void setInsetTime(String insetTime) {
        this.insetTime = Timestamp.valueOf(insetTime);
    }
}