package com.example.dechuan.model.usermanage;

import com.example.dechuan.utils.DateUtils;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;


public class UserManage {
    /**
     *   主键
     *
     */
    private Integer userKy;

    /**
     *   用户code
     */
    private String userCode;

    /**
     *   用户名
     */
    private String userName;

    /**
     *   密码
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String password;
    /**
     *   确认密码
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String confirmPassword;

    /**
     *   电话
     */
    private String telephone;

    /**
     *   手机号
     */
    private String mobilePhone;

    /**
     *   电子邮件
     */
    private String email;

    /**
     *   插入时间
     */
    private Timestamp insertTime;

    /**
     *   更新时间
     */
    private Timestamp updateTime;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private List<UserRole> roleKyList;

    private List<Role> roleList;

    public List<Role> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<Role> roleList) {
        this.roleList = roleList;
    }

    public List<UserRole> getRoleKyList() {
        return roleKyList;
    }

    public void setRoleKyList(List<UserRole> roleKyList) {
        this.roleKyList = roleKyList;
    }

    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    public Integer getUserKy() {
        return userKy;
    }

    public void setUserKy(Integer userKy) {
        this.userKy = userKy;
    }

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.USER_NAME
     *
     * @return the value of tbeh_dc_user.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.USER_NAME
     *
     * @param userName the value for tbeh_dc_user.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.PASSWORD
     *
     * @return the value of tbeh_dc_user.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.PASSWORD
     *
     * @param password the value for tbeh_dc_user.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.TELEPHONE
     *
     * @return the value of tbeh_dc_user.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.TELEPHONE
     *
     * @param telephone the value for tbeh_dc_user.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.MOBILE_PHONE
     *
     * @return the value of tbeh_dc_user.MOBILE_PHONE
     *
     * @mbg.generated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for tbeh_dc_user.MOBILE_PHONE
     *
     * @mbg.generated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.EMAIL
     *
     * @return the value of tbeh_dc_user.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.EMAIL
     *
     * @param email the value for tbeh_dc_user.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.INSERT_TIME
     *
     * @return the value of tbeh_dc_user.INSERT_TIME
     *
     * @mbg.generated
     */



    public String getInsertTime() {
        return DateUtils.formatDate(insertTime, "yyyy-MM-dd HH:mm:ss");
    }


    public void setInsertTime(String insertTime) {
        this.insertTime = Timestamp.valueOf(insertTime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.UPDATE_TIME
     *
     * @return the value of tbeh_dc_user.UPDATE_TIME
     *
     * @mbg.generated
     */

    public String getUpdateTime() {
        return DateUtils.formatDate(updateTime, "yyyy-MM-dd HH:mm:ss");
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = Timestamp.valueOf(updateTime);
    }
}