package com.example.dechuan.model.usermanage;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbeh_dc_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserManage {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.USER_KY
     *
     * @mbg.generated
     */
    private Integer userKy;

    /**
     * Database Column Remarks:
     *   用户code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.USER_CODE
     *
     * @mbg.generated
     */
    private String userCode;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.PASSWORD
     *
     * @mbg.generated
     */
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private String password;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.TELEPHONE
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.MOBILE_PHONE
     *
     * @mbg.generated
     */
    private String mobilePhone;

    /**
     * Database Column Remarks:
     *   电子邮件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.EMAIL
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   插入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.INSERT_TIME
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbeh_dc_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.USER_KY
     *
     * @return the value of tbeh_dc_user.USER_KY
     *
     * @mbg.generated
     */
    public Integer getUserKy() {
        return userKy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.USER_KY
     *
     * @param userKy the value for tbeh_dc_user.USER_KY
     *
     * @mbg.generated
     */
    public void setUserKy(Integer userKy) {
        this.userKy = userKy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.USER_CODE
     *
     * @return the value of tbeh_dc_user.USER_CODE
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.USER_CODE
     *
     * @param userCode the value for tbeh_dc_user.USER_CODE
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.USER_NAME
     *
     * @return the value of tbeh_dc_user.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.USER_NAME
     *
     * @param userName the value for tbeh_dc_user.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.PASSWORD
     *
     * @return the value of tbeh_dc_user.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.PASSWORD
     *
     * @param password the value for tbeh_dc_user.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.TELEPHONE
     *
     * @return the value of tbeh_dc_user.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.TELEPHONE
     *
     * @param telephone the value for tbeh_dc_user.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.MOBILE_PHONE
     *
     * @return the value of tbeh_dc_user.MOBILE_PHONE
     *
     * @mbg.generated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for tbeh_dc_user.MOBILE_PHONE
     *
     * @mbg.generated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.EMAIL
     *
     * @return the value of tbeh_dc_user.EMAIL
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.EMAIL
     *
     * @param email the value for tbeh_dc_user.EMAIL
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.INSERT_TIME
     *
     * @return the value of tbeh_dc_user.INSERT_TIME
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.INSERT_TIME
     *
     * @param insertTime the value for tbeh_dc_user.INSERT_TIME
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbeh_dc_user.UPDATE_TIME
     *
     * @return the value of tbeh_dc_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbeh_dc_user.UPDATE_TIME
     *
     * @param updateTime the value for tbeh_dc_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}