package com.example.dechuan.mapper.usermanage;

import com.example.dechuan.model.usermanage.UserManage;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface UserManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbeh_dc_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userKy);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbeh_dc_user
     *
     * @mbg.generated
     */
    int insert(UserManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbeh_dc_user
     *
     * @mbg.generated
     */
    int insertSelective(UserManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbeh_dc_user
     *
     * @mbg.generated
     */
    List<UserManage> listuser(UserManage userManage);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbeh_dc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbeh_dc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserManage record);
}