package com.example.dechuan.mapper.carimage;

import com.example.dechuan.model.carimage.CarImage;

public interface CarImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truckinout_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer imky);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truckinout_image
     *
     * @mbg.generated
     */
    int insert(CarImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truckinout_image
     *
     * @mbg.generated
     */
    int insertSelective(CarImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truckinout_image
     *
     * @mbg.generated
     */
    CarImage selectByPrimaryKey(Integer imky);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truckinout_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CarImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table truckinout_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CarImage record);
}